name: Push to container registry

on:
  push:
    branches:
      - main


jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
        - uses: actions/checkout@v2

        - run: mkdir -p path/to/artifact

        - run: echo hello > path/to/artifact/world.txt

        - uses: actions/upload-artifact@v2
          with:
            name: my-artifact
            path: path/to/artifact/world.txt
